import { resolve } from "node:path";

export default {
  // Repository instructions are maintained at the root, not generated by Next.
  agentRules: false,
  poweredByHeader: false,
  devIndicators: false,
  turbopack: { root: resolve(import.meta.dirname, "../..") },
};
